// Insert all the variables and the commands at top level into the "syscalls_b_loader" function

// Global variables

var aio_init_addr;
var fpathconf_addr;
var dmem_container_addr;
var evf_clear_addr;
var kqueue_addr;
var kevent_addr;
var futimes_addr;
var open_addr;
var thr_self_addr;
var mkdir_addr;
var pipe_addr;
var stat_addr;
var write_addr;
var evf_cancel_addr;
var ktimer_delete_addr;
var setregid_addr;
var jitshm_create_addr;
var sigwait_addr;
var fdatasync_addr;
var sigtimedwait_addr;
var get_gpo_addr;
var sched_setscheduler_addr;
var osem_open_addr;
var dynlib_get_info_addr;
var osem_post_addr;
var blockpool_move_addr;
var issetugid_addr;
var getdents_addr;
var rtprio_thread_addr;
var evf_delete_addr;
var _umtx_op_addr;
var access_addr;
var reboot_addr;
var sigaltstack_addr;
var getcontext_addr;
var munmap_addr;
var setuid_addr;
var evf_trywait_addr;
var setcontext_addr;
var dynlib_get_list_addr;
var setsid_addr;
var fstatfs_addr;
var aio_multi_wait_addr;
var accept_addr;
var set_phys_fmem_limit_addr;
var thr_get_name_addr;
var get_page_table_stats_addr;
var sigsuspend_addr;
var truncate_addr;
var fsync_addr;
var execve_addr;
var evf_open_addr;
var netabort_addr;
var blockpool_unmap_addr;
var osem_create_addr;
var getlogin_addr;
var mincore_addr;
var shutdown_addr;
var profil_addr;
var preadv_addr;
var geteuid_addr;
var set_chicken_switches_addr;
var sigqueue_addr;
var aio_multi_poll_addr;
var get_self_auth_info_addr;
var opmc_enable_addr;
var aio_multi_delete_addr;
var rfork_addr;
var sys_exit_addr;
var blockpool_batch_addr;
var sigpending_addr;
var ktimer_gettime_addr;
var opmc_set_ctr_addr;
var ksem_wait_addr;
var sched_getparam_addr;
var swapcontext_addr;
var opmc_get_ctr_addr;
var budget_get_ptype_addr;
var msync_addr;
var sigwaitinfo_addr;
var lstat_addr;
var test_debug_rwmem_addr;
var evf_create_addr;
var madvise_addr;
var cpuset_getaffinity_addr;
var evf_set_addr;
var setlogin_addr;
var ksem_init_addr;
var opmc_disable_addr;
var namedobj_delete_addr;
var gettimeofday_addr;
var read_addr;
var thr_get_ucontext_addr;
var batch_map_addr;
var sysarch_addr;
var utc_to_localtime_addr;
var evf_close_addr;
var setrlimit_addr;
var getpeername_addr;
var aio_get_data_addr;
var lseek_addr;
var connect_addr;
var recvfrom_addr;
var getrlimit_addr;
var dynlib_get_info_for_libdbg_addr;
var thr_suspend_ucontext_addr;
var _umtx_op_addr;
var kill_addr;
var dynlib_process_needed_and_relocate_addr;
var getsockname_addr;
var osem_trywait_addr;
var execve_addr;
var flock_addr;
var sigreturn_addr;
var query_memory_protection_addr;
var pwrite_addr;
var get_map_statistics_addr;
var ksem_getvalue_addr;
var sendfile_addr;
var socketex_addr;
var unlink_addr;
var thr_resume_ucontext_addr;
var dl_get_list_addr;
var cpuset_setaffinity_addr;
var clock_gettime_addr;
var thr_kill2_addr;
var set_timezone_info_addr;
var select_addr;
var pselect_addr;
var sync_addr;
var socketpair_addr;
var get_kernel_mem_statistics_addr;
var virtual_query_all_addr;
var physhm_open_addr;
var getuid_addr;
var revoke_addr;
var sigprocmask_addr;
var setegid_addr;
var cpuset_getid_addr;
var evf_wait_addr;
var sched_get_priority_max_addr;
var sigaction_addr;
var ipmimgr_call_addr;
var aio_submit_cmd_addr;
var free_stack_addr;
var settimeofday_addr;
var recvmsg_addr;
var aio_submit_addr;
var setgroups_addr;
var aio_multi_cancel_addr;
var nanosleep_addr;
var blockpool_map_addr;
var thr_create_addr;
var munlockall_addr;
var dynlib_get_info_ex_addr;
var pwritev_addr;
var mname_addr;
var regmgr_call_addr;
var getgroups_addr;
var osem_close_addr;
var osem_delete_addr;
var dynlib_get_obj_member_addr;
var debug_init_addr;
var mmap_dmem_addr;
var kldunloadf_addr;
var mprotect_addr;
var ksem_trywait_addr;
var ksem_close_addr;
var sched_rr_get_interval_addr;
var getitimer_addr;
var getpid_addr;
var netgetsockinfo_addr;
var get_cpu_usage_all_addr;
var eport_delete_addr;
var randomized_path_addr;
var jitshm_alias_addr;
var seteuid_addr;
var set_uevt_addr;
var clock_getres_addr;
var setitimer_addr;
var thr_exit_addr;
var sandbox_path_addr;
var thr_kill_addr;
var sys_exit_addr;
var dup2_addr;
var utimes_addr;
var pread_addr;
var dl_get_info_addr;
var ktimer_settime_addr;
var sched_setparam_addr;
var aio_create_addr;
var osem_wait_addr;
var dynlib_get_list_for_libdbg_addr;
var get_proc_type_info_addr;
var getgid_addr;
var fstat_addr;
var fork_addr;
var namedobj_create_addr;
var opmc_set_ctl_addr;
var get_resident_count_addr;
var getdirentries_addr;
var getrusage_addr;
var setreuid_addr;
var wait4_addr;
var __sysctl_addr;
var bind_addr;
var sched_yield_addr;
var dl_get_metadata_addr;
var get_resident_fmem_count_addr;
var setsockopt_addr;
var dynlib_load_prx_addr;
var getpriority_addr;
var get_phys_page_size_addr;
var opmc_set_hw_addr;
var dynlib_do_copy_relocations_addr;
var netcontrol_addr;
var ksem_post_addr;
var netgetiflist_addr;
var chmod_addr;
var aio_suspend_addr;
var ksem_timedwait_addr;
var dynlib_dlsym_addr;
var get_paging_stats_of_all_objects_addr;
var osem_cancel_addr;
var writev_addr;
var ktimer_getoverrun_addr;
var rmdir_addr;
var sched_get_priority_min_addr;
var dynlib_unload_prx_addr;
var thr_set_name_addr;
var mlockall_addr;
var openat_addr;
var eport_open_addr;
var sigprocmask_addr;
var chdir_addr;
var physhm_unlink_addr;
var mtypeprotect_addr;
var thr_wake_addr;
var blockpool_open_addr;
var thr_new_addr;
var munlock_addr;
var fchflags_addr;
var ftruncate_addr;
var rename_addr;
var poll_addr;
var eport_trigger_addr;
var getsid_addr;
var virtual_query_addr;
var fchmod_addr;
var _umtx_unlock_addr;
var mmap_addr;
var ktimer_create_addr;
var dup_addr;
var sendmsg_addr;
var close_addr;
var is_development_mode_addr;
var getegid_addr;
var get_vm_map_timestamp_addr;
var dynlib_get_proc_param_addr;
var fcntl_addr;
var getppid_addr;
var readv_addr;
var rdup_addr;
var listen_addr;
var app_state_change_addr;
var set_gpo_addr;
var ksem_unlink_addr;
var get_cpu_usage_proc_addr;
var shm_unlink_addr;
var reserve_2mb_page_addr;
var dynlib_get_info2_addr;
var mlock_addr;
var workaround8849_addr;
var get_sdk_compiled_version_addr;
var clock_settime_addr;
var ksem_destroy_addr;
var ksem_open_addr;
var thr_set_ucontext_addr;
var get_bio_usage_all_addr;
var getdtablesize_addr;
var chflags_addr;
var shm_open_addr;
var eport_close_addr;
var dynlib_get_list2_addr;
var socketclose_addr;
var sched_getscheduler_addr;
var pathconf_addr;
var localtime_to_utc_addr;
var setpriority_addr;
var cpumode_yield_addr;
var process_terminate_addr;
var ioctl_addr;
var opmc_get_hw_addr;
var eport_create_addr;
var socket_addr;
var _umtx_lock_addr;
var thr_suspend_addr;
var is_in_sandbox_addr;
var get_authinfo_addr;
var mdbg_service_addr;
var getsockopt_addr;
var get_paging_stats_of_all_threads_addr;
var adjtime_addr;
var kqueueex_addr;
var uuidgen_addr;
var set_vm_container_addr;
var sendto_addr;

function syscalls_b_loader() {
    aio_init_addr = sys_670_addr;
    fpathconf_addr = sys_192_addr;
    dmem_container_addr = sys_586_addr;
    evf_clear_addr = sys_545_addr;
    kqueue_addr = sys_362_addr;
    kevent_addr = sys_363_addr;
    futimes_addr = sys_206_addr;
    open_addr = sys_5_addr;
    thr_self_addr = sys_432_addr;
    mkdir_addr = sys_136_addr;
    pipe_addr = sys_42_addr;
    stat_addr = sys_188_addr;
    write_addr = sys_4_addr;
    evf_cancel_addr = sys_546_addr;
    ktimer_delete_addr = sys_236_addr;
    setregid_addr = sys_127_addr;
    jitshm_create_addr = sys_533_addr;
    sigwait_addr = sys_429_addr;
    fdatasync_addr = sys_658_addr;
    sigtimedwait_addr = sys_345_addr;
    get_gpo_addr = sys_623_addr;
    sched_setscheduler_addr = sys_329_addr;
    osem_open_addr = sys_551_addr;
    dynlib_get_info_addr = sys_593_addr;
    osem_post_addr = sys_555_addr;
    blockpool_move_addr = sys_673_addr;
    issetugid_addr = sys_253_addr;
    getdents_addr = sys_272_addr;
    rtprio_thread_addr = sys_466_addr;
    evf_delete_addr = sys_539_addr;
    _umtx_op_addr = sys_454_addr;
    access_addr = sys_33_addr;
    reboot_addr = sys_55_addr;
    sigaltstack_addr = sys_53_addr;
    getcontext_addr = sys_421_addr;
    munmap_addr = sys_73_addr;
    setuid_addr = sys_23_addr;
    evf_trywait_addr = sys_543_addr;
    setcontext_addr = sys_422_addr;
    dynlib_get_list_addr = sys_592_addr;
    setsid_addr = sys_147_addr;
    fstatfs_addr = sys_397_addr;
    aio_multi_wait_addr = sys_663_addr;
    accept_addr = sys_30_addr;
    set_phys_fmem_limit_addr = sys_637_addr;
    thr_get_name_addr = sys_616_addr;
    get_page_table_stats_addr = sys_671_addr;
    sigsuspend_addr = sys_341_addr;
    truncate_addr = sys_479_addr;
    fsync_addr = sys_95_addr;
    execve_addr = sys_59_addr;
    evf_open_addr = sys_540_addr;
    netabort_addr = sys_101_addr;
    blockpool_unmap_addr = sys_655_addr;
    osem_create_addr = sys_549_addr;
    getlogin_addr = sys_49_addr;
    mincore_addr = sys_78_addr;
    shutdown_addr = sys_134_addr;
    profil_addr = sys_44_addr;
    preadv_addr = sys_289_addr;
    geteuid_addr = sys_25_addr;
    set_chicken_switches_addr = sys_643_addr;
    sigqueue_addr = sys_456_addr;
    aio_multi_poll_addr = sys_664_addr;
    get_self_auth_info_addr = sys_607_addr;
    opmc_enable_addr = sys_563_addr;
    aio_multi_delete_addr = sys_662_addr;
    rfork_addr = sys_251_addr;
    sys_exit_addr = sys_1_addr;
    blockpool_batch_addr = sys_657_addr;
    sigpending_addr = sys_343_addr;
    ktimer_gettime_addr = sys_238_addr;
    opmc_set_ctr_addr = sys_566_addr;
    ksem_wait_addr = sys_402_addr;
    sched_getparam_addr = sys_328_addr;
    swapcontext_addr = sys_423_addr;
    opmc_get_ctr_addr = sys_567_addr;
    budget_get_ptype_addr = sys_610_addr;
    msync_addr = sys_65_addr;
    sigwaitinfo_addr = sys_346_addr;
    lstat_addr = sys_190_addr;
    test_debug_rwmem_addr = sys_619_addr;
    evf_create_addr = sys_538_addr;
    madvise_addr = sys_75_addr;
    cpuset_getaffinity_addr = sys_487_addr;
    evf_set_addr = sys_544_addr;
    setlogin_addr = sys_50_addr;
    ksem_init_addr = sys_404_addr;
    opmc_disable_addr = sys_564_addr;
    namedobj_delete_addr = sys_558_addr;
    gettimeofday_addr = sys_116_addr;
    read_addr = sys_3_addr;
    thr_get_ucontext_addr = sys_634_addr;
    batch_map_addr = sys_548_addr;
    sysarch_addr = sys_165_addr;
    utc_to_localtime_addr = sys_638_addr;
    evf_close_addr = sys_541_addr;
    setrlimit_addr = sys_195_addr;
    getpeername_addr = sys_31_addr;
    aio_get_data_addr = sys_665_addr;
    lseek_addr = sys_478_addr;
    connect_addr = sys_98_addr;
    recvfrom_addr = sys_29_addr;
    getrlimit_addr = sys_194_addr;
    dynlib_get_info_for_libdbg_addr = sys_656_addr;
    thr_suspend_ucontext_addr = sys_632_addr;
    _umtx_op_addr = sys_454_addr;
    kill_addr = sys_37_addr;
    dynlib_process_needed_and_relocate_addr = sys_599_addr;
    getsockname_addr = sys_32_addr;
    osem_trywait_addr = sys_554_addr;
    execve_addr = sys_59_addr;
    flock_addr = sys_131_addr;
    sigreturn_addr = sys_417_addr;
    query_memory_protection_addr = sys_547_addr;
    pwrite_addr = sys_476_addr;
    get_map_statistics_addr = sys_642_addr;
    ksem_getvalue_addr = sys_407_addr;
    sendfile_addr = sys_393_addr;
    socketex_addr = sys_113_addr;
    unlink_addr = sys_10_addr;
    thr_resume_ucontext_addr = sys_633_addr;
    dl_get_list_addr = sys_535_addr;
    cpuset_setaffinity_addr = sys_488_addr;
    clock_gettime_addr = sys_232_addr;
    thr_kill2_addr = sys_481_addr;
    set_timezone_info_addr = sys_636_addr;
    select_addr = sys_93_addr;
    pselect_addr = sys_522_addr;
    sync_addr = sys_36_addr;
    socketpair_addr = sys_135_addr;
    get_kernel_mem_statistics_addr = sys_646_addr;
    virtual_query_all_addr = sys_674_addr;
    physhm_open_addr = sys_629_addr;
    getuid_addr = sys_24_addr;
    revoke_addr = sys_56_addr;
    sigprocmask_addr = sys_340_addr;
    setegid_addr = sys_182_addr;
    cpuset_getid_addr = sys_486_addr;
    evf_wait_addr = sys_542_addr;
    sched_get_priority_max_addr = sys_332_addr;
    sigaction_addr = sys_416_addr;
    ipmimgr_call_addr = sys_622_addr;
    aio_submit_cmd_addr = sys_669_addr;
    free_stack_addr = sys_620_addr;
    settimeofday_addr = sys_122_addr;
    recvmsg_addr = sys_27_addr;
    aio_submit_addr = sys_661_addr;
    setgroups_addr = sys_80_addr;
    aio_multi_cancel_addr = sys_666_addr;
    nanosleep_addr = sys_240_addr;
    blockpool_map_addr = sys_654_addr;
    thr_create_addr = sys_430_addr;
    munlockall_addr = sys_325_addr;
    dynlib_get_info_ex_addr = sys_608_addr;
    pwritev_addr = sys_290_addr;
    mname_addr = sys_588_addr;
    regmgr_call_addr = sys_532_addr;
    getgroups_addr = sys_79_addr;
    osem_close_addr = sys_552_addr;
    osem_delete_addr = sys_550_addr;
    dynlib_get_obj_member_addr = sys_649_addr;
    debug_init_addr = sys_560_addr;
    mmap_dmem_addr = sys_628_addr;
    kldunloadf_addr = sys_444_addr;
    mprotect_addr = sys_74_addr;
    ksem_trywait_addr = sys_403_addr;
    ksem_close_addr = sys_400_addr;
    sched_rr_get_interval_addr = sys_334_addr;
    getitimer_addr = sys_86_addr;
    getpid_addr = sys_20_addr;
    netgetsockinfo_addr = sys_102_addr;
    get_cpu_usage_all_addr = sys_627_addr;
    eport_delete_addr = sys_581_addr;
    randomized_path_addr = sys_602_addr;
    jitshm_alias_addr = sys_534_addr;
    seteuid_addr = sys_183_addr;
    set_uevt_addr = sys_640_addr;
    clock_getres_addr = sys_234_addr;
    setitimer_addr = sys_83_addr;
    thr_exit_addr = sys_431_addr;
    sandbox_path_addr = sys_600_addr;
    thr_kill_addr = sys_433_addr;
    sys_exit_addr = sys_1_addr;
    dup2_addr = sys_90_addr;
    utimes_addr = sys_138_addr;
    pread_addr = sys_475_addr;
    dl_get_info_addr = sys_536_addr;
    ktimer_settime_addr = sys_237_addr;
    sched_setparam_addr = sys_327_addr;
    aio_create_addr = sys_668_addr;
    osem_wait_addr = sys_553_addr;
    dynlib_get_list_for_libdbg_addr = sys_672_addr;
    get_proc_type_info_addr = sys_612_addr;
    getgid_addr = sys_47_addr;
    fstat_addr = sys_189_addr;
    fork_addr = sys_2_addr;
    namedobj_create_addr = sys_557_addr;
    opmc_set_ctl_addr = sys_565_addr;
    get_resident_count_addr = sys_613_addr;
    getdirentries_addr = sys_196_addr;
    getrusage_addr = sys_117_addr;
    setreuid_addr = sys_126_addr;
    wait4_addr = sys_7_addr;
    __sysctl_addr = sys_202_addr;
    bind_addr = sys_104_addr;
    sched_yield_addr = sys_331_addr;
    dl_get_metadata_addr = sys_604_addr;
    get_resident_fmem_count_addr = sys_615_addr;
    setsockopt_addr = sys_105_addr;
    dynlib_load_prx_addr = sys_594_addr;
    getpriority_addr = sys_100_addr;
    get_phys_page_size_addr = sys_677_addr;
    opmc_set_hw_addr = sys_625_addr;
    dynlib_do_copy_relocations_addr = sys_596_addr;
    netcontrol_addr = sys_99_addr;
    ksem_post_addr = sys_401_addr;
    netgetiflist_addr = sys_125_addr;
    chmod_addr = sys_15_addr;
    aio_suspend_addr = sys_315_addr;
    ksem_timedwait_addr = sys_441_addr;
    dynlib_dlsym_addr = sys_591_addr;
    get_paging_stats_of_all_objects_addr = sys_618_addr;
    osem_cancel_addr = sys_556_addr;
    writev_addr = sys_121_addr;
    ktimer_getoverrun_addr = sys_239_addr;
    rmdir_addr = sys_137_addr;
    sched_get_priority_min_addr = sys_333_addr;
    dynlib_unload_prx_addr = sys_595_addr;
    thr_set_name_addr = sys_464_addr;
    mlockall_addr = sys_324_addr;
    openat_addr = sys_499_addr;
    eport_open_addr = sys_583_addr;
    sigprocmask_addr = sys_340_addr;
    chdir_addr = sys_12_addr;
    physhm_unlink_addr = sys_630_addr;
    mtypeprotect_addr = sys_379_addr;
    thr_wake_addr = sys_443_addr;
    blockpool_open_addr = sys_653_addr;
    thr_new_addr = sys_455_addr;
    munlock_addr = sys_204_addr;
    fchflags_addr = sys_35_addr;
    ftruncate_addr = sys_480_addr;
    rename_addr = sys_128_addr;
    poll_addr = sys_209_addr;
    eport_trigger_addr = sys_582_addr;
    getsid_addr = sys_310_addr;
    virtual_query_addr = sys_572_addr;
    fchmod_addr = sys_124_addr;
    _umtx_unlock_addr = sys_435_addr;
    mmap_addr = sys_477_addr;
    ktimer_create_addr = sys_235_addr;
    dup_addr = sys_41_addr;
    sendmsg_addr = sys_28_addr;
    close_addr = sys_6_addr;
    is_development_mode_addr = sys_606_addr;
    getegid_addr = sys_43_addr;
    get_vm_map_timestamp_addr = sys_624_addr;
    dynlib_get_proc_param_addr = sys_598_addr;
    fcntl_addr = sys_92_addr;
    getppid_addr = sys_39_addr;
    readv_addr = sys_120_addr;
    rdup_addr = sys_603_addr;
    listen_addr = sys_106_addr;
    app_state_change_addr = sys_648_addr;
    set_gpo_addr = sys_617_addr;
    ksem_unlink_addr = sys_406_addr;
    get_cpu_usage_proc_addr = sys_641_addr;
    shm_unlink_addr = sys_483_addr;
    reserve_2mb_page_addr = sys_675_addr;
    dynlib_get_info2_addr = sys_660_addr;
    mlock_addr = sys_203_addr;
    workaround8849_addr = sys_605_addr;
    get_sdk_compiled_version_addr = sys_647_addr;
    clock_settime_addr = sys_233_addr;
    ksem_destroy_addr = sys_408_addr;
    ksem_open_addr = sys_405_addr;
    thr_set_ucontext_addr = sys_635_addr;
    get_bio_usage_all_addr = sys_667_addr;
    getdtablesize_addr = sys_89_addr;
    chflags_addr = sys_34_addr;
    shm_open_addr = sys_482_addr;
    eport_close_addr = sys_584_addr;
    dynlib_get_list2_addr = sys_659_addr;
    socketclose_addr = sys_114_addr;
    sched_getscheduler_addr = sys_330_addr;
    pathconf_addr = sys_191_addr;
    localtime_to_utc_addr = sys_639_addr;
    setpriority_addr = sys_96_addr;
    cpumode_yield_addr = sys_676_addr;
    process_terminate_addr = sys_652_addr;
    ioctl_addr = sys_54_addr;
    opmc_get_hw_addr = sys_626_addr;
    eport_create_addr = sys_580_addr;
    socket_addr = sys_97_addr;
    _umtx_lock_addr = sys_434_addr;
    thr_suspend_addr = sys_442_addr;
    is_in_sandbox_addr = sys_585_addr;
    get_authinfo_addr = sys_587_addr;
    mdbg_service_addr = sys_601_addr;
    getsockopt_addr = sys_118_addr;
    get_paging_stats_of_all_threads_addr = sys_611_addr;
    adjtime_addr = sys_140_addr;
    kqueueex_addr = sys_141_addr;
    uuidgen_addr = sys_392_addr;
    set_vm_container_addr = sys_559_addr;
    sendto_addr = sys_133_addr;
}
